version: "3"

services:
  lindacraft-server:
    image: marctv/minecraft-papermc-server:latest
    restart: unless-stopped
    container_name: LindaCraft-server
    environment:
      TZ: Europe/Stockholm
      MEMORYSIZE: "6G"
      PAPERMC_FLAGS: ""
      PUID: "1000"
      PGID: "1000"
      SKIP_PERM_CHECK: "true"
    network_mode: "host"
    volumes:
      - ./server:/data
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
